package dev.kavrin.banking_ledger.audit.domain.model;

public enum AuditEventType {
    ACCOUNT_CREATED,
    LEDGER_TRANSACTION_POSTED,
    TRANSFER_REVERSED,
    ADJUSTMENT_POSTED,
    RECONCILIATION_BATCH_IMPORTED,
    RECONCILIATION_COMPLETED,
    RECONCILIATION_FAILED
}
